name: Close PR
on:
  pull_request:
    types:
      - closed
jobs:
  do_cleanup:
    name: Do cleanup
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          role-session-name: PullRequestCleanupSession

      - name: Remove unused resources
        run: make ci-pull-request-closed
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
